Convert OOB enums from panics to runtime errors
Arwalk/zig-protobuf pull request #76
Opened 2024-10-28 15:07 UTC by hans-tvs

2024-10-28 19:39 UTC, Arwalk requested changes
Excellent! Some minor changes requested. Thank you for catching this problem and fixing it.

2024-10-28 19:39 UTC, Arwalk commented on src/protobuf.zig
> +fn decode_varint_value(comptime T: type, comptime varint_type: VarintType, raw: u64) !T {
polish: Can we make the error type explicit instead of inferred? I'd like to make a pass on all the method to make them explicits in the near future.

2024-10-28 19:39 UTC, Arwalk commented on src/protobuf.zig
> +            .Enum => if ((raw >> 32) != 0)
suggestion: wouldn't it be clearer to use [std.math.maxInt(i32)](https://ziglang.org/documentation/master/std/#std.math.maxInt)?

```zig
.Enum => if(raw > std.math.maxInt(i32))
```

2024-10-28 19:46 UTC, menduz commented on src/protobuf.zig
> +                @as(T, @enumFromInt(@as(i32, @bitCast(@as(u32, @intCast(raw)))))),
Why is there a new bitCast?

2024-10-28 19:47 UTC, menduz reviewed
Could you add some comments about the motivations for the changeset? the motivation is not evident in the tests

2024-10-29 04:06 UTC, hans-tvs commented
Thanks for the suggestions. I took another pass at this.

> explicit error type

I used that particular error literal because it fit the problem well and appeared many times throughout the code. Does re-using the `DecodingError` you already have defined work here?

> `std.math.maxInt(i32)`
> Why is there a new bitcast?

These are related. It's valid for protobuf enums to have negative values, and the previous `@intCast` didn't suffice for those. The solution here uses an `@intCast`, as before`, to drop from 64 to 32 bits (cost varies from architecture to architecture, but it's cheap), and a `@bitCast` to assert that those bits are actually signed (free at runtime except in some esoteric microcontrollers and whatnot).

Regarding your suggestion, comparing to `std.math.maxInt(u32)` (not the signed version) seems reasonable.

> Can you add some comments about the motivations for the changeset?

I added comments in code for one of the tests; the other test was just a new test for existing behavior (mainly for my benefit, ensuring I hadn't made any egregious errors, but it usually doesn't hurt to add those tests upstream). I'm not totally sure what you're looking for, so would you mind taking a peek and explaining why that comment does or does not work?

2024-10-29 11:48 UTC, menduz approved these changes
Many thanks for the revisions

2024-10-29 12:24 UTC, Arwalk approved these changes

2024-10-29 12:24 UTC, merged

2024-10-29 12:25 UTC, Arwalk commented
Thanks again for your contribution.

2024-10-31 19:32 UTC, hans-tvs commented
Thank you so much for the fast review and for building this project in the first place :)